# Generated by Django 5.2.4 on 2025-08-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Register Plan', 'verbose_name_plural': 'Register Plan'},
        ),
    ]
